### ISSUE TITLE
Cannot find module 'babel-core' 

### ISSUE THREAD

**Issue by jamiechong** [acoustep/ember-cli-foundation-6-sass#35]
I tried to install and got this error right away: 

```
$ ember install ember-cli-foundation-6-sass
Installed packages for tooling via npm.
Cannot find module 'babel-core'
Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/...../node_modules/ember-cli-foundation-6-sass/index.js:5:13)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Using:
```
ember-cli: 2.9.1
node: 6.9.1
```

**Comment by jamiechong** [comment]
@localpcguy @acoustep I'm guessing this issue was introduced with #34. My ember install is pretty basic - have you guys tested with a clean install?

**Comment by localpcguy** [comment]
Quick fix is likely to `npm install babel-core` but it's likely the project I was testing #34 in already had it installed. I actually need to test this again tomorrow anyways in order to get it merged in for the end of our sprint, so I'll take a look - probably needs some package.json updates to ensure all the right packages are included (in addition to babel it also likely needs the babel add-ons included.)

**Comment by localpcguy** [comment]
Looks like this is an issue with Node v4, I was on Node v6 and a fresh install worked. But I was able to get the error on Node v4. I did notice I accidentally put the dependencies in the `devDependencies` section, not the `dependencies` section, so that is also likely an issue. Just wanted to update, I don't quite have the PR ready, but have been looking at this.
